# Generated by Django 5.0.1 on 2024-02-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_feather'),
    ]

    operations = [
        migrations.AddField(
            model_name='feather',
            name='fact',
            field=models.CharField(default=[0], max_length=160),
        ),
        migrations.AlterField(
            model_name='feather',
            name='type',
            field=models.CharField(choices=[('F', 'Flight Feathers'), ('C', 'Contour Feathers'), ('D', 'Down Feathers')], default='F', max_length=1),
        ),
    ]
