# Generated by Django 5.0.1 on 2024-02-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_feather_fact_alter_feather_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='duck',
            name='feathers',
            field=models.ManyToManyField(to='main_app.feather'),
        ),
    ]
